{% set name = "flake8-colors" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35a5483a7d156d0438b402faea2fefe45b411571ce5dc93ba28670fd9429cc46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - flake8-colors = flake8_colors:ColorFormatter

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8 >3.0.0
    - python  >=3.6

test:
  imports:
    - flake8_colors
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/and3rson/flake8-colors
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Error highlight plugin for Flake8.

extra:
  recipe-maintainers:
    - marcelotrevisani
