travis:
  secure:
    BINSTAR_TOKEN: SXB08QAGqCEm5X1giWqQUIGF39u6EyRWkpuqW6reBB98HqwbiZVlUHjlUDH8UJPk+5JMfcr4133Kak9g8craBhISz2tRNhvkEbbreG2oYPBCHyDJyZR9gddPkxrRWK7WRaUR/CAYzapnojUfAfYZejE/gEDKi1Fq/AunNm4B8roB376LPQqfLH3KAigNJ9D3Zogh1yDUQF0OTiR04LydFTz2LSe3vMfhFC0mytt6TIRiDU/JkSC0RG13MlNV9omBGa65/hQj2MtLqBEgIEjYrqte7EwbTZ9EGrETrCcP0kOaANB0HiXtlkZRQTq8GkeuxyB/fsff23amTl4XOPGYmCbQcdtSi0Tpr/zAU47CqE1SMeiUXtYvdJl2xz9u143wPXn2095ZQwJXEWkbXHAAg70/c1fF84GrFEjdHx/FjiopPKrFjFU1HprbhimRVDfE5sS/8kSwf7FQyoU45N7TnV/tldRYrFkioE3vtX3RR3oTQPTcbJpuoQgBo68jEDsMr95AOxd/fEZa5I7tgFM4ON+PABxBKx4bmlYyhBxwKyA3T6bkF8x/SA/ihYc8IwvbhJfK9PW3pqqqDdlUOZOdlCiMLCWoBEFvoMIwCGVCUv5DOg2R5AEiSA5wa8ip0XHTCfx4gYeafwtD/MfNYteDaSuhtZsifGspcG10LSAXDew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
